from pathlib import Path

p = Path("assistant.py")
s = p.read_text(encoding="utf-8")
old = '''    def web_search(self, query):\n        url = f"https://www.google.com/search?q={query.strip().replace(' ', '+')}"\n        signals.open_url.emit(url)\n        return f"Recherche web exécutée pour : {query}"\n'''
new = '''    def web_search(self, query):\n        """Search the web for real results, then expose the first result URLs to the UI."""\n        try:\n            from core.web_search import WebSearchProvider\n            provider = WebSearchProvider(timeout=8.0)\n            results = provider.search(query, limit=6)\n            for result in results[:3]:\n                try:\n                    signals.open_url.emit(result.url)\n                except Exception:\n                    pass\n            lines = [f"{i}. {r.title}\\n{r.url}\\n{r.snippet}" for i, r in enumerate(results, 1)]\n            return f"Résultats web via {provider.last_provider} pour « {query} » :\\n\\n" + "\\n\\n".join(lines)\n        except Exception as exc:\n            log.warning(f"Recherche web échouée: {exc}")\n            return f"Recherche web indisponible : {exc}"\n'''
if old not in s:
    raise SystemExit("web_search target not found")
s = s.replace(old, new, 1)

old_tts = '''            if PYGAME_OK:\n                if not pygame.mixer.get_init():\n                    pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=1024)\n                pygame.mixer.music.load(str(path))\n                pygame.mixer.music.set_volume(1.0)\n                pygame.mixer.music.play()\n                while pygame.mixer.music.get_busy():\n                    if stop_event.is_set() or state.abort_requested:\n                        pygame.mixer.music.stop()\n                        break\n                    await asyncio.sleep(0.05)\n'''
new_tts = '''            played = False\n            if PYGAME_OK:\n                try:\n                    if not pygame.mixer.get_init():\n                        pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=1024)\n                    pygame.mixer.music.load(str(path))\n                    pygame.mixer.music.set_volume(1.0)\n                    pygame.mixer.music.play()\n                    played = True\n                    log.info("TTS: lecture audio démarrée via pygame")\n                    while pygame.mixer.music.get_busy():\n                        if stop_event.is_set() or state.abort_requested:\n                            pygame.mixer.music.stop()\n                            break\n                        await asyncio.sleep(0.05)\n                except Exception as playback_error:\n                    log.warning(f"TTS lecture pygame échouée: {playback_error}")\n\n            if not played and sys.platform == "win32":\n                # Dernier recours: synthèse Windows, pour garantir une sortie vocale\n                # même si le backend pygame/audio MP3 est indisponible.\n                try:\n                    import subprocess as _subprocess\n                    safe_text = text.replace("'", "''")\n                    ps = (\n                        "Add-Type -AssemblyName System.Speech; "\n                        "$s=New-Object System.Speech.Synthesis.SpeechSynthesizer; "\n                        "$s.Volume=100; $s.Rate=0; "\n                        f"$s.Speak('{safe_text}')"\n                    )\n                    log.warning("TTS: fallback Windows Speech activé")\n                    _subprocess.run(["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", ps], timeout=120, check=False)\n                except Exception as fallback_error:\n                    log.error(f"TTS fallback Windows échoué: {fallback_error}")\n'''
if old_tts not in s:
    raise SystemExit("tts target not found")
s = s.replace(old_tts, new_tts, 1)
p.write_text(s, encoding="utf-8")
