# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['assistant.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'sitecustomize',
        'core.action_engine',
        'core.agent_engine',
        'core.conversation_session',
        'core.conversation_ai',
        'core.runtime_conversation_bridge',
        'core.goal_planner',
        'core.groq_planner',
        'core.groq_provider',
        'core.ollama_planner',
        'core.neo_capabilities',
        'core.web_search',
        'core.voice_session_bridge',
        'core.runtime_ui_bridge',
        'core.windows_autostart',
        'ui.discrete_hud',
        'ui.provider_settings',
        'ui.arc_reactor',
        'ui.neo_hud',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['sitecustomize.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='JARVIS_NEO',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
